# Generated by Django 4.2.11 on 2024-11-01 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0002_alter_depositproducts_fin_prdt_cd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositoptions',
            old_name='fin_prdt_dc',
            new_name='fin_prdt_cd',
        ),
    ]
